version: '3.8'
services:
  backend:
    container_name: NodeExpressTypeScriptStarterKit-Backend
    build:
      dockerfile: Dockerfile
      context: .
    ports:
      - '3092:5500'
    volumes:
      - /app
      - /app/node_modules
    env_file:
      - .env
    depends_on:
      - postgres

  postgres:
    image: postgres:16.1-alpine3.19
    restart: always
    container_name: postgres
    volumes:
      - data:/data/db
    environment:
      - 'POSTGRES_DB=postgres'
      - 'POSTGRES_USER=postgres'
      - 'POSTGRES_PASSWORD=postgres'
    ports:
      - '3093:5432'

volumes:
  data:
